---
- name: Retrieve Secret from Vault
  hosts: localhost
  gather_facts: true
  become: true

  tasks:
    - name: Include Vaulted Variables
      include_vars:
        file: secret.yml

    - name: Display the Secret
      debug:
        msg: "The secret password is {{ password }}"
